// Common Nigerian banks & fintechs for bank-transfer payouts.
export interface Bank {
  name: string;
  code?: string;
}

export const NIGERIAN_BANKS: Bank[] = [
  { name: "Access Bank", code: "044" },
  { name: "Access Bank (Diamond)", code: "063" },
  { name: "ALAT by Wema", code: "035A" },
  { name: "Carbon", code: "565" },
  { name: "Citibank Nigeria", code: "023" },
  { name: "Ecobank Nigeria", code: "050" },
  { name: "Fairmoney Microfinance Bank", code: "51318" },
  { name: "Fidelity Bank", code: "070" },
  { name: "First Bank of Nigeria", code: "011" },
  { name: "First City Monument Bank (FCMB)", code: "214" },
  { name: "Globus Bank", code: "00103" },
  { name: "Guaranty Trust Bank (GTBank)", code: "058" },
  { name: "Heritage Bank", code: "030" },
  { name: "Jaiz Bank", code: "301" },
  { name: "Keystone Bank", code: "082" },
  { name: "Kuda Microfinance Bank", code: "50211" },
  { name: "Lotus Bank", code: "303" },
  { name: "Moniepoint Microfinance Bank", code: "50515" },
  { name: "Opay (Paycom)", code: "999992" },
  { name: "Optimus Bank", code: "107" },
  { name: "Palmpay", code: "999991" },
  { name: "Parallex Bank", code: "104" },
  { name: "Polaris Bank", code: "076" },
  { name: "PremiumTrust Bank", code: "105" },
  { name: "Providus Bank", code: "101" },
  { name: "Rubies Microfinance Bank", code: "125" },
  { name: "Sparkle Microfinance Bank", code: "51310" },
  { name: "Stanbic IBTC Bank", code: "221" },
  { name: "Standard Chartered Bank", code: "068" },
  { name: "Sterling Bank", code: "232" },
  { name: "SunTrust Bank", code: "100" },
  { name: "TAJ Bank", code: "302" },
  { name: "Titan Trust Bank", code: "102" },
  { name: "Union Bank of Nigeria", code: "032" },
  { name: "United Bank For Africa (UBA)", code: "033" },
  { name: "Unity Bank", code: "215" },
  { name: "VFD Microfinance Bank", code: "566" },
  { name: "Wema Bank", code: "035" },
  { name: "Zenith Bank", code: "057" },
  { name: "9 Payment Service Bank (9PSB)", code: "120001" },
  { name: "Abbey Mortgage Bank", code: "801" },
  { name: "AB Microfinance Bank", code: "51204" },
  { name: "Above Only Microfinance Bank" },
  { name: "Accion Microfinance Bank", code: "602" },
  { name: "Ahmadu Bello University Microfinance Bank" },
  { name: "Amju Unique Microfinance Bank" },
  { name: "Aramoko Microfinance Bank" },
  { name: "ASO Savings and Loans", code: "401" },
  { name: "Astrapolaris Microfinance Bank" },
  { name: "Bowen Microfinance Bank" },
  { name: "CEMCS Microfinance Bank" },
  { name: "Chikum Microfinance Bank" },
  { name: "Coronation Merchant Bank" },
  { name: "Covenant Microfinance Bank" },
  { name: "Eyowo", code: "50126" },
  { name: "Firmus Microfinance Bank" },
  { name: "FSDH Merchant Bank" },
  { name: "Gateway Mortgage Bank" },
  { name: "GoMoney", code: "100022" },
  { name: "Hackman Microfinance Bank" },
  { name: "Hasal Microfinance Bank" },
  { name: "Ibile Microfinance Bank" },
  { name: "Ikoyi Osun Microfinance Bank" },
  { name: "Infinity Microfinance Bank" },
  { name: "Kredi Money Microfinance Bank" },
  { name: "Lagos Building Investment Company (LBIC)" },
  { name: "Links Microfinance Bank" },
  { name: "Mayfair Microfinance Bank" },
  { name: "Mint Microfinance Bank" },
  { name: "Paga", code: "100002" },
  { name: "PatrickGold Microfinance Bank" },
  { name: "Peace Microfinance Bank" },
  { name: "Personal Trust Microfinance Bank" },
  { name: "Petra Microfinance Bank" },
  { name: "Quickfund Microfinance Bank" },
  { name: "Rand Merchant Bank" },
  { name: "Regent Microfinance Bank" },
  { name: "Rephidim Microfinance Bank" },
  { name: "Safe Haven Microfinance Bank" },
  { name: "Safe Haven MFB" },
  { name: "Seedvest Microfinance Bank" },
  { name: "Stellas Microfinance Bank" },
  { name: "TCF Microfinance Bank" },
  { name: "Trust Microfinance Bank" },
  { name: "Uhuru Microfinance Bank" },
  { name: "Unaab Microfinance Bank" },
  { name: "Unical Microfinance Bank" },
  { name: "Uzondu Microfinance Bank" },
  { name: "Verite Microfinance Bank" },
  { name: "Vist Financial Trust" },
  { name: "Xslnce Microfinance Bank" },
  { name: "Zinternet – KongaPay" },
];
